name: Update template
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  invoke:
    name: Invoke update
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: https://registry.npmjs.org/
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create project (release)
        run: |
          rm ./nuxt.config.js
          npx @shopware-pwa/cli@latest init --ci
          ls -l
