name: Update template
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  invoke:
    name: Invoke update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Update template
        run: |
          rm ./nuxt.config.js
          npx @shopware-pwa/cli init --ci
          git diff
